title: Data Science Portfolio
description: Documenting my learning in Data Science
theme: pages-themes/cayman@v0.2.0
logo: profile.png
author: Samantha Kaplan
show_downloads: false
github:
  is_project_page: false
social_links:
  github: https://github.com/skaplan6-lab
  linkedin: https://linkedin.com/in/samanthakaplan558


